import { useState, type FormEvent } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../api/client';
import type { ApiResponse, LoginResponse } from '../api/types';

export function AcceptInvitationPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (password !== confirmPassword) { setError('Passwords do not match.'); return; } const token = params.get('token'); if (!token) { setError('This invitation link is invalid.'); return; } setIsSubmitting(true); setError(null); try { const response = await api.post<ApiResponse<LoginResponse>>('/auth/invitations/accept', { token, password }); localStorage.setItem('auth_token', response.data.data.token); navigate('/dashboard', { replace: true }); } catch { setError('This invitation is invalid, expired, or already accepted.'); } finally { setIsSubmitting(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-zinc-100 p-4"><form className="w-full max-w-md rounded-lg border border-zinc-200 bg-white p-6 shadow-sm" onSubmit={submit}><h1 className="text-xl font-semibold">Set up your account</h1><p className="mt-1 text-sm text-zinc-500">Choose a password to accept your staff invitation.</p><label className="mt-5 block text-sm font-medium">Password<input className="mt-1 w-full rounded-md border border-zinc-300 px-3 py-2" type="password" minLength={8} value={password} onChange={(e) => setPassword(e.target.value)} required /></label><label className="mt-4 block text-sm font-medium">Confirm password<input className="mt-1 w-full rounded-md border border-zinc-300 px-3 py-2" type="password" minLength={8} value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} required /></label>{error && <p className="mt-3 text-sm text-rose-700">{error}</p>}<button className="mt-5 w-full rounded-md bg-zinc-900 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60" disabled={isSubmitting}>{isSubmitting ? 'Creating account...' : 'Accept invitation'}</button></form></main>;
}
