import { useState, type FormEvent } from 'react';
import { api } from '../api/client';
import type { ManagedUser } from '../api/types';
import { DataState } from '../components/DataState';
import { PageHeader } from '../components/PageHeader';
import { useApiResource } from '../hooks/useApiResource';

const blank = { email: '', fullName: '', phone: '', position: '', role: 'STAFF' };
export function StaffAccessPage() {
  const { data, isLoading, error, reload } = useApiResource<ManagedUser[]>('/auth/users');
  const [form, setForm] = useState(blank); const [message, setMessage] = useState<string | null>(null); const [isSending, setIsSending] = useState(false);
  async function invite(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setIsSending(true); setMessage(null); try { await api.post('/auth/invitations', form); setForm(blank); setMessage('Invitation sent.'); await reload(); } catch { setMessage('Unable to send invitation. Confirm SMTP is configured and the email is unused.'); } finally { setIsSending(false); } }
  async function updateRole(id: string, role: 'STAFF' | 'MANAGER') { await api.patch(`/auth/users/${id}/role`, { role }); await reload(); }
  return <><PageHeader title="Staff access" description="Invite staff by email and manage operational access." />{message && <p className="mb-4 rounded-md bg-zinc-100 p-3 text-sm text-zinc-700">{message}</p>}<div className="grid gap-6 xl:grid-cols-[360px_1fr]"><section className="rounded-lg border border-zinc-200 bg-white p-5"><h2 className="font-semibold">Invite team member</h2><form className="mt-4 space-y-3" onSubmit={invite}>{(['email','fullName','phone','position'] as const).map((field) => <input key={field} className="w-full rounded-md border border-zinc-300 px-3 py-2 text-sm" placeholder={field === 'fullName' ? 'Full name' : field === 'position' ? 'Position (e.g. Backend Developer)' : field[0].toUpperCase() + field.slice(1)} type={field === 'email' ? 'email' : 'text'} value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })} required />)}<select className="w-full rounded-md border border-zinc-300 px-3 py-2 text-sm" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="STAFF">Staff</option><option value="MANAGER">Manager</option></select><button className="w-full rounded-md bg-zinc-900 px-3 py-2 text-sm font-semibold text-white disabled:opacity-60" disabled={isSending}>{isSending ? 'Sending...' : 'Send invitation'}</button></form></section><DataState isLoading={isLoading} error={error} isEmpty={!data?.length} emptyMessage="No invited staff accounts yet."><section className="overflow-hidden rounded-lg border border-zinc-200 bg-white"><table className="min-w-full text-sm"><thead className="bg-zinc-50 text-left text-xs uppercase text-zinc-500"><tr><th className="p-3">Person</th><th className="p-3">Position</th><th className="p-3">Access</th></tr></thead><tbody>{data?.map((user) => <tr className="border-t" key={user.id}><td className="p-3"><p className="font-medium">{user.fullName}</p><p className="text-zinc-500">{user.email}</p></td><td className="p-3">{user.position ?? '-'}</td><td className="p-3"><select className="rounded border border-zinc-300 px-2 py-1" value={user.role} onChange={(e) => void updateRole(user.id, e.target.value as 'STAFF' | 'MANAGER')}><option value="STAFF">Staff</option><option value="MANAGER">Manager</option></select></td></tr>)}</tbody></table></section></DataState></div></>;
}
